Classification


*   We have to initialize the k value.(k>0)
*   Find the k nearest neighbour from the new data.
*   From those k how many neighbours belongs to 1 category and 2 category.



Distance Metrics

*   Euclidean Distance
*   Manhattan Distance



In [1]:
#Classifier

In [3]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [4]:
from sklearn.datasets import make_classification
X,y = make_classification(
    n_samples=1000, #1000 observation
    n_features = 3,# total independent features
    n_redundant= 1,
    n_classes = 2, # binary target /label
    random_state = 42

    )

In [5]:
X.shape

(1000, 3)

In [6]:
y.shape

(1000,)

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3, random_state = 42)

In [9]:
from sklearn.neighbors import KNeighborsClassifier

In [10]:
KNeighborsClassifier()

KNeighborsClassifier()

In [11]:
classifier = KNeighborsClassifier()
classifier.fit(X_train,y_train)

KNeighborsClassifier()

In [12]:
y_pred = classifier.predict(X_test)

In [13]:
y_pred

array([1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0])

In [14]:
y_test

array([1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0])

In [15]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [16]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[138  14]
 [ 13 135]]
0.91
              precision    recall  f1-score   support

           0       0.91      0.91      0.91       152
           1       0.91      0.91      0.91       148

    accuracy                           0.91       300
   macro avg       0.91      0.91      0.91       300
weighted avg       0.91      0.91      0.91       300



In [17]:
#GridSearchCV
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings('ignore')

In [26]:
parameters = {
    'n_neighbors':list(range(30)),
    'p': [1,2],
    'weights': ['uniform','distance']

}

In [27]:
clf = GridSearchCV(classifier,param_grid = parameters)

In [28]:
# Splitting of train data to validation data
clf.fit(X_train,y_train)

GridSearchCV(estimator=KNeighborsClassifier(n_neighbors=25, p=1),
             param_grid={'n_neighbors': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
                                         12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
                                         22, 23, 24, 25, 26, 27, 28, 29],
                         'p': [1, 2], 'weights': ['uniform', 'distance']})

In [29]:
clf.best_params_

{'n_neighbors': 7, 'p': 2, 'weights': 'uniform'}

In [30]:
classifier = KNeighborsClassifier(n_neighbors = 25,p =1)

In [31]:
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=25, p=1)

In [32]:
#Prediction
y_pred = classifier.predict(X_test)
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[143  21]
 [  8 128]]
0.9033333333333333
              precision    recall  f1-score   support

           0       0.95      0.87      0.91       164
           1       0.86      0.94      0.90       136

    accuracy                           0.90       300
   macro avg       0.90      0.91      0.90       300
weighted avg       0.91      0.90      0.90       300



In [34]:
# Import pickle for saving and loading the model
import pickle
# Save the trained model to a pickle file
with open('knn.pkl','wb') as file:
  pickle.dump(classifier,file)
print(f"Model saved to knn.pkl")

Model saved to knn.pkl


In [35]:
# Load the model from the pickel file
with open('knn.pkl','rb') as file:
  loaded_model = pickle.load(file)

In [37]:
# Test the loaded model with predictions
y_pred_loaded = loaded_model.predict(X_test)
print(y_pred_loaded)

[1 0 1 1 1 0 0 1 1 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 1 1 0 1 0 0 1 0 0 1
 1 1 1 0 1 0 0 0 1 1 0 1 0 0 1 1 0 1 0 0 1 0 1 1 1 1 0 1 1 0 0 0 1 0 0 0 1
 1 0 0 0 0 1 0 1 0 0 1 1 1 1 0 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0 1 1 1 0 0 1 0
 1 0 0 0 1 1 0 1 0 1 1 0 1 0 0 1 1 1 0 1 1 0 0 0 1 0 0 0 1 1 0 0 1 0 1 1 1
 0 0 1 0 1 0 0 0 1 1 1 1 1 1 1 0 1 0 0 1 0 0 1 1 0 0 1 0 0 0 1 0 1 1 1 1 1
 1 0 0 1 1 1 1 0 1 0 1 0 0 1 0 0 1 0 0 0 0 0 1 1 1 0 0 0 1 0 1 1 0 0 1 1 0
 1 0 1 0 1 1 1 0 1 0 1 1 1 0 1 0 0 0 1 1 0 1 0 0 0 1 0 0 1 1 1 0 0 0 0 1 1
 0 0 0 0 0 0 0 1 1 0 0 1 1 0 1 0 0 1 0 0 0 0 1 0 0 1 1 1 0 0 0 0 1 0 0 0 0
 0 1 1 0]


In [38]:
loaded_model.predict([[1,2,3]])

array([1])

In [39]:
loaded_model.predict([[4,2,1]])

array([1])