Aim --> To solve Classification Problem
  

*   For Example:
*   Will a student pass or fail ?
*   Is an email spam or not?   
*   Does a patient have a desease or not?







Despite the name, it is used for classification, not regression.


*   Step 1: Make  Linear Prediction Like in Linear Regression, we calculate a value z using the formula:


*   Z
*   w1x1+ w2x2 +...+wnxn+b

  *   x1,x2,..,xn are the input features
  *   w1,w2,...,wn are the weights
  *   b os the bias
  *   z is the linear combination of inputs


Step 2: Apply the sigmoid function To Convert z into a probability (Between 0 and 1), we use the sigmoid function:


*   o-(z)= 1/(1+e^-z)
*   This converts the output to a number between 0 and 1.








*   if the output is close tyo 1--> predict class 1(e.g;"Yes").
*   if the output is close tyo 0--> predict class 0(e.g;"No").

*   We usually use a 0.5 threshold.
*   Dataset --> 2 features


*   No.of Players Hours-----------Results

*   9-----------------------------fail

*   8-----------------------------fail

*   7-----------------------------fail

*   6-----------------------------fail
*   5-----------------------------Pass


*   4-----------------------------pass


*   1-----------------------------pass


*   2-----------------------------fail








Two Types of classification



*   Binary Classification
*   Multiclass Classification



If there is imbalance dataset we don't focus on accuracy we use precision and recall.

false Positive is important in precision and False Negative is important in recall.

Spam Classification:


*   Mail is spam and model predict as spam.--> Good Scenario.

*   Mail is not spam but model predicts spam. Important mail may be missed.(Blunder).In this scenario false positive is important. So we must reduce it. Hence we use Precision.
*   Mail is spam ,model predicts not a spam.(Not much effect)




Diabetes Prediction


*   Person suffered from diabetes and model also predicts suffring from diabetese--> Good scenario

*   Person suffered from diabetes and model also predicts no suffring from diabetese--> Blunder, false negative should be reduced. Hence we use recall.
*   Actually person has no diabetes but model predicts suffering from diabetes.(Not much effect)


*   Hyperparameter Tuning --> Find the best parameters while trainning the model


    *   GridSearchCV
    *   RandomizedSearchCV



*   Disadvantage
  *   Time complexity increses for trainning the model.


*   RandomizedSearchCV --> Time Complexity Decrease









In [1]:
from sklearn.datasets import load_iris

In [2]:
dataset = load_iris()

In [3]:
dataset

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [4]:
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

In [5]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [6]:
import pandas as pd
import numpy as np


In [7]:
dataset.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [8]:
df = pd.DataFrame(dataset.data,columns=dataset.feature_names)

In [9]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [10]:
df['target'] = dataset.target

In [11]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [12]:
df['target'].value_counts()

target
0    50
1    50
2    50
Name: count, dtype: int64

In [14]:
dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

Binary Classification

In [16]:
df['target'] != 2

0       True
1       True
2       True
3       True
4       True
       ...  
145    False
146    False
147    False
148    False
149    False
Name: target, Length: 150, dtype: bool

In [17]:
df_copy = df[df['target'] != 2]

In [18]:
df_copy.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [19]:
df_copy.shape

(100, 5)

In [20]:
df_copy['target'].value_counts()

target
0    50
1    50
Name: count, dtype: int64

In [21]:
df_copy.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
95                5.7               3.0                4.2               1.2   
96                5.7               2.9                4.2               1.3   
97                6.2               2.9                4.3               1.3   
98                5.1               2.5                3.0               1.1   
99                5.7               2.8                4.1               1.3   

    target  
95       1  
96       1  
97       1  
98       1  
99       1

In [22]:
df_copy.target

0     0
1     0
2     0
3     0
4     0
     ..
95    1
96    1
97    1
98    1
99    1
Name: target, Length: 100, dtype: int64

In [23]:
df_copy.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [24]:
df_copy['target'].unique()

array([0, 1])

In [25]:
df_copy

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 5.1               3.5                1.4               0.2   
1                 4.9               3.0                1.4               0.2   
2                 4.7               3.2                1.3               0.2   
3                 4.6               3.1                1.5               0.2   
4                 5.0               3.6                1.4               0.2   
..                ...               ...                ...               ...   
95                5.7               3.0                4.2               1.2   
96                5.7               2.9                4.2               1.3   
97                6.2               2.9                4.3               1.3   
98                5.1               2.5                3.0               1.1   
99                5.7               2.8                4.1               1.3   

    target  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
95       1  
96       1  
97       1  
98       1  
99       1  

[100 rows x 5 columns]

Independent and Dependent Features

In [26]:
X = df_copy.iloc[:,:-1]
y = df_copy.iloc[:,-1]

In [27]:
X

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                 5.1               3.5                1.4               0.2
1                 4.9               3.0                1.4               0.2
2                 4.7               3.2                1.3               0.2
3                 4.6               3.1                1.5               0.2
4                 5.0               3.6                1.4               0.2
..                ...               ...                ...               ...
95                5.7               3.0                4.2               1.2
96                5.7               2.9                4.2               1.3
97                6.2               2.9                4.3               1.3
98                5.1               2.5                3.0               1.1
99                5.7               2.8                4.1               1.3

[100 rows x 4 columns]

In [28]:
y

0     0
1     0
2     0
3     0
4     0
     ..
95    1
96    1
97    1
98    1
99    1
Name: target, Length: 100, dtype: int64

In [29]:
from sklearn.linear_model import LogisticRegression

In [48]:
# train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [49]:
X_train

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
55                5.7               2.8                4.5               1.3
88                5.6               3.0                4.1               1.3
26                5.0               3.4                1.6               0.4
42                4.4               3.2                1.3               0.2
69                5.6               2.5                3.9               1.1
..                ...               ...                ...               ...
60                5.0               2.0                3.5               1.0
71                6.1               2.8                4.0               1.3
14                5.8               4.0                1.2               0.2
92                5.8               2.6                4.0               1.2
51                6.4               3.2                4.5               1.5

[80 rows x 4 columns]

In [50]:
X_test

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
83                6.0               2.7                5.1               1.6
53                5.5               2.3                4.0               1.3
70                5.9               3.2                4.8               1.8
45                4.8               3.0                1.4               0.3
44                5.1               3.8                1.9               0.4
39                5.1               3.4                1.5               0.2
22                4.6               3.6                1.0               0.2
80                5.5               2.4                3.8               1.1
10                5.4               3.7                1.5               0.2
0                 5.1               3.5                1.4               0.2
18                5.7               3.8                1.7               0.3
30                4.8               3.1                1.6               0.2
73                6.1               2.8                4.7               1.2
33                5.5               4.2                1.4               0.2
90                5.5               2.6                4.4               1.2
4                 5.0               3.6                1.4               0.2
76                6.8               2.8                4.8               1.4
77                6.7               3.0                5.0               1.7
12                4.8               3.0                1.4               0.1
31                5.4               3.4                1.5               0.4

In [51]:
y_train

55    1
88    1
26    0
42    0
69    1
     ..
60    1
71    1
14    0
92    1
51    1
Name: target, Length: 80, dtype: int64

In [52]:
y_test

83    1
53    1
70    1
45    0
44    0
39    0
22    0
80    1
10    0
0     0
18    0
30    0
73    1
33    0
90    1
4     0
76    1
77    1
12    0
31    0
Name: target, dtype: int64

In [53]:
classifier = LogisticRegression()

In [54]:
classifier

LogisticRegression()

In [55]:
classifier.fit(X_train,y_train)

LogisticRegression()

In [56]:
#prediction
y_pred = classifier.predict(X_test)

In [57]:
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

In [58]:
list(y_test)

[1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0]

In [59]:
classifier.predict_proba(X_test)

array([[0.00118455, 0.99881545],
       [0.01579803, 0.98420197],
       [0.00304709, 0.99695291],
       [0.96959941, 0.03040059],
       [0.94269372, 0.05730628],
       [0.97161144, 0.02838856],
       [0.99356322, 0.00643678],
       [0.0316902 , 0.9683098 ],
       [0.97460702, 0.02539298],
       [0.9789308 , 0.0210692 ],
       [0.95512884, 0.04487116],
       [0.96072669, 0.03927331],
       [0.00430743, 0.99569257],
       [0.98586374, 0.01413626],
       [0.00927792, 0.99072208],
       [0.98146423, 0.01853577],
       [0.00207948, 0.99792052],
       [0.00125531, 0.99874469],
       [0.97461564, 0.02538436],
       [0.96116169, 0.03883831]])

confusion matrix, ccuracy score, classification report

In [60]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [61]:
print(confusion_matrix(y_test,y_pred))

[[12  0]
 [ 0  8]]


In [62]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [63]:
print(accuracy_score(y_test,y_pred))

1.0


Hyperparameter Tuning

In [64]:
## GridSearchCV
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings('ignore')

In [65]:
parameters = {
    'penalty':['l1','l2','elasticnet',None],
    'dual':[True,False],
    'C' : [1,10,20,30,40,50],
    'max_iter' : [100,200,300,1000,10000]
    }

In [67]:
clf = GridSearchCV(classifier,param_grid = parameters)

In [68]:
clf

GridSearchCV(estimator=LogisticRegression(),
             param_grid={'C': [1, 10, 20, 30, 40, 50], 'dual': [True, False],
                         'max_iter': [100, 200, 300, 1000, 10000],
                         'penalty': ['l1', 'l2', 'elasticnet', None]})

In [69]:
## splitting of train data to validation data
clf.fit(X_train, y_train)

GridSearchCV(estimator=LogisticRegression(),
             param_grid={'C': [1, 10, 20, 30, 40, 50], 'dual': [True, False],
                         'max_iter': [100, 200, 300, 1000, 10000],
                         'penalty': ['l1', 'l2', 'elasticnet', None]})

In [70]:
clf.best_params_

{'C': 1, 'dual': False, 'max_iter': 100, 'penalty': 'l2'}

In [71]:
classifier = LogisticRegression(C =1, penalty = 'l2',max_iter = 100,dual = False)


In [72]:
classifier.fit(X_train, y_train)

LogisticRegression(C=1)

In [74]:
# prediction
y_pred = classifier.predict(X_test)
print(confusion_matrix(y_pred, y_test))
print(accuracy_score(y_pred, y_test))
print(classification_report(y_pred, y_test))

[[12  0]
 [ 0  8]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [75]:
# Randomized Search CV
from sklearn.model_selection import RandomizedSearchCV

In [76]:
random_clf = RandomizedSearchCV(LogisticRegression(),param_distributions = parameters)

In [77]:
random_clf.fit(X_train,y_train)

RandomizedSearchCV(estimator=LogisticRegression(),
                   param_distributions={'C': [1, 10, 20, 30, 40, 50],
                                        'dual': [True, False],
                                        'max_iter': [100, 200, 300, 1000,
                                                     10000],
                                        'penalty': ['l1', 'l2', 'elasticnet',
                                                    None]})

In [78]:
random_clf.best_params_

{'penalty': None, 'max_iter': 200, 'dual': False, 'C': 1}

In [79]:
classifier = LogisticRegression(C=20,penalty ='l2',max_iter = 1000)

In [80]:
y_pred = classifier.predict(X_test)
print(confusion_matrix(y_pred, y_test))
print(accuracy_score(y_pred, y_test))
print(classification_report(y_pred, y_test))

[[12  0]
 [ 0  8]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [83]:
#Import pickle for saving and loading the model
import pickle
# File for saving the model
pickle_file = 'logistic.pkl'
#save the trained model to a pickle file
with open(pickle_file,'wb') as file:
  pickle.dump(classifier,file)
print(f"Model saved to {pickle_file}")

Model saved to logistic.pkl


In [84]:
#Load the model from the pickle file
with open(pickle_file,'rb') as file:
  loaded_model = pickle.load(file)

In [85]:
#Testthe loaded model with prediction
y_pred_loaded = loaded_model.predict(X_test)
print(y_pred_loaded)

[1 1 1 0 0 0 0 1 0 0 0 0 1 0 1 0 1 1 0 0]


In [86]:
X.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [88]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

In [91]:
y_pred_loaded

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

In [92]:
list(y_test)

[1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0]

In [96]:
y_pred_loaded = loaded_model.predict([[6.1,2.8,4.7,1.2]])

In [97]:
X_test

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
83                6.0               2.7                5.1               1.6
53                5.5               2.3                4.0               1.3
70                5.9               3.2                4.8               1.8
45                4.8               3.0                1.4               0.3
44                5.1               3.8                1.9               0.4
39                5.1               3.4                1.5               0.2
22                4.6               3.6                1.0               0.2
80                5.5               2.4                3.8               1.1
10                5.4               3.7                1.5               0.2
0                 5.1               3.5                1.4               0.2
18                5.7               3.8                1.7               0.3
30                4.8               3.1                1.6               0.2
73                6.1               2.8                4.7               1.2
33                5.5               4.2                1.4               0.2
90                5.5               2.6                4.4               1.2
4                 5.0               3.6                1.4               0.2
76                6.8               2.8                4.8               1.4
77                6.7               3.0                5.0               1.7
12                4.8               3.0                1.4               0.1
31                5.4               3.4                1.5               0.4

In [98]:
y_pred_loaded = loaded_model.predict([[5.4,3.7,1.5,0.2]])
print(y_pred_loaded)


[0]


In [99]:
y_test

83    1
53    1
70    1
45    0
44    0
39    0
22    0
80    1
10    0
0     0
18    0
30    0
73    1
33    0
90    1
4     0
76    1
77    1
12    0
31    0
Name: target, dtype: int64